databases:
  - name: django_render_db
    plan: free
    databaseName: django_render_db
    user: django_user
    region: singapore

services:
  - type: web
    plan: free
    region: singapore
    name: django_user
    branch: main
    healthCheckPath: /
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_render_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true